# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build Rust lib
  build:
    steps:
      name: Build Rust lib
      runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
    
      # Test Rust lib
      name: Test Rust lib
      - uses: actions-rs/cargo@v1
        with:
          command: test
    
    # Build WASM module
      name: Test WASM module
      - uses: jetli/wasm-pack-action@v0.3.0
      - name: build wasm
        run: |
          cd wasm/
          wasm-pack build --out-dir ../lisper-web/pkg/ --target bundler
    
    # Deploy preview build
      name: Deploy preview
      - uses: amondnet/vercel-action@v20
        if: github.event_name == 'pull_request_target'
        id: deployment-preview
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./lisper-web/
    
    # Deploy production build
      name: Deploy production
      - uses: amondnet/vercel-action@v20
        if: github.event_name == 'push'
        id: deployment-production
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          vercel-args: '--prod'
          working-directory: ./lisper-web/
